#!/bin/bash
#Use as ./build <revision> <bintrayUser> <bintrayKey>
cd "$( dirname "${BASH_SOURCE[0]}" )"

git clone https://github.com/Victorious3/VChat.git ./VChat
cd ./VChat
git reset --hard "$1"
cd ../

./gradlew -PbintrayUser="$2" -PbintrayKey="$3" :VChat:build :VChat:bintrayUpload
